[package]
name = "implot-sys-bindgen"
version = "0.7.0"
authors = ["Sandro Merkli"]
edition = "2018"

[dependencies]
bindgen = "0.69.4"
imgui-sys = { git = "https://github.com/JosiahWhite/imgui-rs.git", rev = "9b7fad059faa692de6e431ac55ee2690e216a6c7", features = ["docking"] }
